import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {evaluateDax,visibleRows,parseDax} from '../public/app/dax.js';import {graphTemplate} from '../public/app/graph.js';
const data=JSON.parse(fs.readFileSync(new URL('../public/packs/fixtures.json',import.meta.url)));const graph=()=>graphTemplate('model');
const measure=(code,country='All',category='All',g=graph())=>evaluateDax(code,data,g,{country,category}).value;
test('revenue is quantity times price, not sum of prices',()=>{assert.equal(measure('Revenue = SUMX(Sales, Sales[Quantity]*Sales[UnitPrice])'),410);assert.notEqual(measure('Revenue = SUM(Sales[UnitPrice])'),410);});
test('gross profit and margin reference agree with fixture arithmetic',()=>{assert.equal(measure('Preview = [Gross Profit]'),196);assert.equal(measure('Margin = DIVIDE([Gross Profit],[Revenue])'),196/410);});
test('active customer relationship applies country filter',()=>{assert.equal(measure('Preview = [Revenue]','Norway'),300);assert.equal(measure('Preview = [Revenue]','Sweden'),110);});
test('category and country filters intersect',()=>{assert.equal(measure('Preview = [Revenue]','Norway','Hardware'),200);assert.equal(measure('Preview = [Revenue]','Sweden','Accessories'),60);});
test('inactive relationship stops country propagation',()=>{const g=graph();g.edges.find(e=>e.from==='customer').active=false;assert.equal(measure('Preview = [Revenue]','Norway','All',g),410);});
test('no rows: SUM, SUMX, DISTINCTCOUNT and COUNTROWS return BLANK',()=>{for(const code of ['SUM(Sales[Quantity])','SUMX(Sales,Sales[Quantity])','DISTINCTCOUNT(Sales[OrderKey])','COUNTROWS(Sales)'])assert.equal(measure(code,'Denmark'),null);});
test('DIVIDE handles blank and zero denominators',()=>{assert.equal(measure('DIVIDE(1,0)'),null);assert.equal(measure('DIVIDE(1,0,99)'),99);assert.equal(measure('DIVIDE([Gross Profit],[Revenue])','Denmark'),null);});
test('CALCULATE replaces same-column filter instead of intersecting',()=>{assert.equal(measure('CALCULATE([Revenue],DimCustomer[Country]="Norway")','Sweden'),300);});
test('CALCULATE preserves unrelated category filter',()=>{assert.equal(measure('CALCULATE([Revenue],DimCustomer[Country]="Norway")','Sweden','Hardware'),200);});
test('arithmetic precedence and unary minus',()=>{assert.equal(measure('2+3*4'),14);assert.equal(measure('-(2+3)*4'),-20);});
test('table, column and function names are case-insensitive in teaching fixture',()=>assert.equal(measure('sumx(sales, sales[quantity]*sales[unitprice])'),410));
test('unsupported valid DAX is distinguished from a failed answer',()=>{assert.throws(()=>measure('AVERAGEX(Sales,Sales[Quantity])'),/not implemented/);assert.throws(()=>measure('CALCULATE([Revenue],KEEPFILTERS(DimCustomer[Country]="Norway"))'),/Only simple/);});
test('context transition is explicitly unsupported, never approximated',()=>{assert.throws(()=>measure('SUMX(Sales,[Revenue])'),/context transition/);assert.throws(()=>measure('SUMX(Sales,CALCULATE([Revenue],DimCustomer[Country]="Norway"))'),/outside/);});
test('circular and unknown measures rejected',()=>{assert.throws(()=>measure('Revenue = [Revenue]'),/Circular/);assert.throws(()=>measure('[No Such Measure]'),/Unknown/);});
test('scalar column references need row context',()=>assert.throws(()=>measure('Sales[Quantity]'),/row context/));
test('bad syntax, non-finite numbers and excessive nesting rejected',()=>{for(const code of ['alert(1);','2/0','1+','"text"','('.repeat(50)+'1'+')'.repeat(50)])assert.throws(()=>measure(code));});
test('parser preserves measure display name',()=>assert.equal(parseDax('Gross Margin = DIVIDE([Gross Profit],[Revenue])').name,'Gross Margin'));
test('visible table rows correspond to slicers',()=>{assert.equal(visibleRows('DimCustomer',data,graph(),{country:'Norway',category:'All'}).length,2);assert.equal(visibleRows('Sales',data,graph(),{country:'Denmark',category:'All'}).length,0);});
