import test from 'node:test';import assert from 'node:assert/strict';
import {graphTemplate,topologicalLayers,simulateDAG,graphChecks,parseDiagram,toDiagram,toMermaid,graphSVG,performanceModel,autoLayout} from '../public/app/graph.js';
test('all teaching templates form acyclic graphs',()=>{for(const t of ['model','pipeline','watermark','dbt','fabric','databricks','bigquery','infrastructure','spark','lakehouse'])assert.ok(topologicalLayers(graphTemplate(t)).length);});
test('DAG fixture deliberately fails quality gate and allows bypass',()=>{const g=graphTemplate('pipeline');assert.ok(graphChecks(g,'pipeline').some(c=>!c.passed));const runs=simulateDAG(g);assert.equal(runs.find(r=>r.id==='quality').status,'failed');assert.equal(runs.find(r=>r.id==='publish').status,'success');});
function repaired(){const g=graphTemplate('pipeline');g.edges=g.edges.filter(e=>!(e.from==='transform'&&e.to==='publish'));g.edges.push({id:'repair',from:'quality',to:'publish'});return g;}
test('repairing dependency blocks publish until quality succeeds',()=>{const g=repaired();assert.ok(graphChecks(g,'pipeline').every(c=>c.passed));assert.equal(simulateDAG(g).find(r=>r.id==='publish').status,'upstream_failed');});
test('one retry recovers a transient failure and releases publish',()=>{const g=repaired();g.nodes.find(n=>n.id==='quality').retries=1;const run=simulateDAG(g);assert.ok(run.every(r=>r.status==='success'));assert.equal(run.find(r=>r.id==='quality').attempts,2);assert.ok(run.find(r=>r.id==='publish').start>=run.find(r=>r.id==='quality').end);});
test('cycle refused, including after importing structure',()=>{const g=repaired();g.edges.push({id:'cycle',from:'publish',to:'extract'});assert.throws(()=>simulateDAG(g),/Cycle/);assert.equal(graphChecks(g,'pipeline')[0].passed,false);});
test('parallel branches start together; join waits for longest',()=>{const g=parseDiagram('a[A] -> b[B]\na -> c[C]\nb -> d[D]\nc -> d');g.nodes.find(n=>n.id==='b').duration=9;const runs=simulateDAG(g);assert.equal(runs.find(r=>r.id==='b').start,runs.find(r=>r.id==='c').start);assert.equal(runs.find(r=>r.id==='d').start,12);});
test('disabled edge is ignored by topological ordering',()=>{const g=parseDiagram('a[A] -> b[B]');g.edges.push({id:'cycle',from:'b',to:'a',active:false});assert.equal(topologicalLayers(g).length,2);});
test('diagram parser preserves position and role of stable node IDs',()=>{const old=graphTemplate('fabric');old.nodes[0].x=199;const g=parseDiagram(toDiagram(old).replace('Operational source','New source'),old);assert.equal(g.nodes[0].x,199);assert.equal(g.nodes[0].role,'source');assert.equal(g.nodes[0].label,'New source');});
test('diagram parser rejects JavaScript, unsafe identifiers and self edges',()=>{for(const text of ['alert(1)','a --> b','a[A] -> a','constructor[No]',''])assert.throws(()=>parseDiagram(text));});
test('duplicate diagram edges are deduplicated',()=>assert.equal(parseDiagram('a -> b\na -> b').edges.length,1));
test('SVG export escapes hostile labels',()=>{const g=parseDiagram('a[<img onerror="bad">]');const svg=graphSVG(g);assert.ok(svg.includes('&lt;img'));assert.ok(!svg.includes('<img'));assert.ok(!toMermaid(g).includes('<img'));});
test('structure checks require an end-to-end path',()=>{const g=graphTemplate('fabric');assert.ok(graphChecks(g,'fabric').every(c=>c.passed));g.edges=[];assert.equal(graphChecks(g,'fabric').at(-1).passed,false);});
test('auto layout preserves nodes, roles and edges without mutating',()=>{const g=graphTemplate('fabric');g.nodes[0].x=999;const out=autoLayout(g);assert.equal(g.nodes[0].x,999);assert.equal(out.nodes[0].x,35);assert.deepEqual(out.edges,g.edges);});
test('Spark toy formula remains positive across all controls',()=>{for(let p=2;p<=12;p++)for(let skew=0;skew<=80;skew+=5)for(const b of [false,true]){const values=performanceModel(p,skew,b);assert.equal(values.length,p);assert.ok(values.every(n=>n>=4));}});
test('toy skew raises longest task; broadcast lowers modeled work',()=>{assert.ok(Math.max(...performanceModel(6,60,false))>Math.max(...performanceModel(6,0,false)));assert.ok(Math.max(...performanceModel(6,60,true))<Math.max(...performanceModel(6,60,false)));});
