import { escapeHTML as e,formatNumber,validateGraph } from '../core.js';
import { aheadBehind,commitAt,gitDiff,gitFixture,gitGraphSVG,headId,runGit } from '../git.js';
import { graphSVG } from '../graph.js';
import { notice,options,pre,steps,table } from '../ui.js';
import type { ViewContext } from './context.js';

export function gitPanel(ctx:ViewContext):string{
 const s=ctx.git();if(ctx.labTab==='Predict')return gitPredictionPanel(ctx);if(ctx.labTab==='Diff')return `<div class="panel-scroll"><h3>Working tree &rarr; index</h3>${pre(gitDiff(s.index,s.files)||'No unstaged changes.')}<h3>Index &rarr; HEAD</h3>${pre(gitDiff(commitAt(s,headId(s)).tree,s.index)||'No staged changes.')}</div>`;
 if(ctx.labTab==='Files'){ctx.selectedFile=Object.hasOwn(s.files,ctx.selectedFile)?ctx.selectedFile:Object.keys(s.files)[0];return `<div class="virtual-file-view"><label>Working-tree file<select id="git-file">${options(Object.keys(s.files),ctx.selectedFile)}</select></label><textarea id="virtual-file" class="code-fallback" aria-label="Virtual Git working-tree file">${e(s.files[ctx.selectedFile]??'')}</textarea><div class="inline-actions"><button class="primary" data-action="save-git-file">Save working file</button><button class="secondary" data-action="stage-file">Stage this file</button><span class="muted">Saving changes the working tree, not the index.</span></div></div>`;}
 const refs=aheadBehind(s,s.branches.main??headId(s),s.tracking['origin/main']??headId(s));const c=s.commits.find(c=>c.id===ctx.selectedCommit);
 return `<div class="git-workspace"><div class="git-summary"><span class="chip">SIMULATION</span><strong>HEAD &rarr; ${e(s.head??'detached at '+headId(s))}</strong><span class="muted">main: ${refs.ahead} ahead / ${refs.behind} behind tracking</span></div><div class="git-graph">${gitGraphSVG(s,ctx.selectedCommit)}</div><div class="git-middle"><div class="commit-inspector">${c?`<span class="eyebrow">COMMIT ${e(c.id)}</span><strong>${e(c.message)}</strong><p>Parent${c.parents.length===1?'':'s'}: ${e(c.parents.join(', ')||'none')}</p><p>${e(Object.keys(c.tree).join(', '))}</p>`:`<span class="eyebrow">CONNECTED STATE</span><p>Click a commit to inspect its parents and snapshot. Run commands to move real simulated refs.</p>`}</div><div class="git-state-summary"><div><span>Working tree</span><strong>${Object.keys(s.files).length} files</strong></div><div><span>Index</span><strong>${Object.keys(s.index).length} files</strong></div><div><span>Commits</span><strong>${s.commits.length}</strong></div></div></div><div class="terminal-console" aria-live="polite">${s.history.length?s.history.slice(-12).map(x=>pre(x)).join(''):'<p>Virtual Git ready. Type <code>git status</code> or <code>git help</code>.</p>'}</div><form class="command-line" id="git-form"><label for="git-command">git &gt;</label><input id="git-command" autocomplete="off" spellcheck="false" placeholder="git status" aria-label="Virtual Git command"><button class="primary" type="submit">Run command</button></form><div class="lab-footnote">No host, GitHub or remote access. Merge conflicts are whole-file teaching conflicts; rebase supports linear history only.</div></div>`;
}

export function gitPredictions(ctx:ViewContext):{id:string;label:string}[]{const goal=ctx.current.fixture?.goal;const correct=goal==='fetch'?{id:'tracking',label:'Only the remote-tracking reference and fetched objects change.'}:goal==='rebase'?{id:'replay',label:'The feature changes are replayed onto main with new commit IDs.'}:goal==='staged-only'?{id:'index',label:'The commit contains the staged index, not every working-tree file.'}:goal==='rescue'?{id:'branch',label:'A new named branch points to the ctx.current commit and HEAD becomes attached.'}:{id:'parents',label:'A new commit records both parent histories; existing commits keep their IDs.'};return [correct,{id:'rewrite-all',label:'All existing commit IDs are rewritten and their snapshots are mutated.'},{id:'working-only',label:'Only the working files change; references and history never change.'}];}

export function gitPredictionPanel(ctx:ViewContext):string{
 const choices=gitPredictions(ctx),ordered=[choices[1],choices[0],choices[2]];let target=gitFixture(ctx.current.fixture?.git);
 const perform=(cmd:string)=>{const r=runGit(target,cmd);if(r.ok)target=r.state;};
 if(ctx.current.fixture?.goal==='merge'){perform('git merge feature');if(target.pendingMerge){target.files['pipeline.py']='print("ingest and validate")\n';perform('git add pipeline.py');perform('git commit -m "Resolved merge"');}}
 if(ctx.current.fixture?.goal==='rebase')perform('git rebase main');if(ctx.current.fixture?.goal==='fetch')perform('git fetch');if(ctx.current.fixture?.goal==='rescue')perform('git switch -c rescue');if(ctx.current.fixture?.goal==='staged-only'){perform('git add pipeline.py');perform('git commit -m "Validation"');}
 return `<div class="panel-scroll"><span class="eyebrow">PREDICT BEFORE YOU CHANGE IT</span><h3>What should change when you reach this goal?</h3><div class="choice-list">${ordered.map(c=>`<label class="choice"><input type="radio" name="git-prediction" value="${e(c.id)}" ${ctx.draft().gitPrediction===c.id?'checked':''}><span>${e(c.label)}</span></label>`).join('')}</div><div class="inline-actions" style="margin-top:12px"><button class="secondary" data-action="check-prediction">Check my prediction</button></div><div id="prediction-feedback"></div><details><summary>View target topology (not the command solution)</summary>${gitGraphSVG(target)}<p class="muted">Target state is a separate reference fixture. It never changes your live virtual repository. Branch and commit names may differ in an equivalent solution.</p></details></div>`;
}

export function terminalPanel(ctx:ViewContext):string{const s=ctx.terminal();if(ctx.labTab==='Files'){ctx.selectedFile=Object.hasOwn(s.files,ctx.selectedFile)?ctx.selectedFile:Object.keys(s.files)[0];return `<div class="virtual-file-view"><label>Virtual filesystem<select id="terminal-file">${options(Object.keys(s.files),ctx.selectedFile)}</select></label><textarea id="virtual-file" class="code-fallback" aria-label="Virtual shell file">${e(s.files[ctx.selectedFile]??'')}</textarea><div class="inline-actions"><button class="primary" data-action="save-terminal-file">Save virtual file</button><span class="muted">No access to your actual disk.</span></div></div>`;}
 return `<div class="terminal-workspace"><div class="terminal-heading"><label>Shell<select id="shell-select">${options(['bash','powershell'],s.shell)}</select></label><span class="chip">VIRTUAL FILESYSTEM</span><button class="text-button" data-action="open-git">Open Git Lab</button></div><div class="terminal-console" aria-live="polite">${s.history.length?s.history.map(h=>`<div class="console-entry ${h.ok?'':'console-error'}"><div class="console-command">${e(s.shell==='bash'?'$':'PS>')} ${e(h.command)}</div><span class="output-type">${e(h.type)}</span>${pre(h.output)}</div>`).join(''):`<h3>${s.shell==='bash'?'Bash text streams':'PowerShell object pipelines'}</h3><p>Practice against small local ctx.fixtures, with no operating-system access.</p><p>Type <code>${s.shell==='bash'?'help':'Get-Help'}</code> for the supported command vocabulary.</p>`}</div><form class="command-line" id="terminal-form"><label for="terminal-command">${s.shell==='bash'?'$':'PS&gt;'}</label><input id="terminal-command" autocomplete="off" spellcheck="false" aria-label="Virtual shell command" placeholder="${s.shell==='bash'?'cat pipeline.log':'Get-Content pipeline.log'}"><button type="submit" class="primary">Run command</button></form><div class="lab-footnote">${s.shell==='bash'?'Text-stream simulation. Literal grep, simple pipes and a small safe command vocabulary.':'Object-pipeline simulation. This is not a full PowerShell interpreter; formatting is not converted to text between stages.'}</div></div>`;
}

export function performancePanel(ctx:ViewContext):string{const f=ctx.current.fixture??{},tasks=f.tasks??[],max=Math.max(1,...tasks.map((t:any)=>Number(t.duration_s)||0));return `<div class="panel-scroll"><div class="section-header"><span class="eyebrow">PERFORMANCE INVESTIGATOR</span><span class="chip">Supplied observation fixture</span></div><div class="metric-cards">${(Array.isArray(f.metrics)?f.metrics:Object.entries(f.metrics??{}).map(([label,value])=>({label,value}))).map((m:any)=>`<div><span>${e(m.label)}</span><strong>${e(m.value)}</strong></div>`).join('')}</div><h3>Task duration distribution</h3><div class="task-bars">${tasks.map((t:any)=>`<div><span>Task ${e(t.task)}</span><div><i style="width:${Math.max(2,100*Number(t.duration_s)/max)}%"></i></div><strong>${e(formatNumber(t.duration_s))} s</strong></div>`).join('')}</div><h3>Which explanation matches the evidence?</h3><div class="choice-list">${(f.diagnoses??[]).map((d:any)=>`<label class="choice"><input type="radio" name="diagnosis-choice" value="${e(d.id)}" ${ctx.draft().answer===d.id?'checked':''}><span>${e(d.label)}</span></label>`).join('')}</div><label class="stacked-label">What would you inspect next?<textarea id="diagnosis" placeholder="Name the next metric or plan detail, and one trade-off...">${e(ctx.draft().diagnosis??'')}</textarea></label><p class="muted">The chart visualizes supplied measurements. It does not predict the effect of changing partitions or cluster size.</p></div>`;}

export function configEvidence(ctx:ViewContext):string{const f=ctx.current.fixture??{};return `<div class="panel-scroll">${notice('Supplied evidence, not regenerated output','Editing your draft does not run a cloud provider, rebuild an image, replan resources or update this evidence.')}${f.graph?graphSVG(validateGraph(f.graph)):''}${f.events?'<h3>Events</h3>'+table(f.events):''}${f.logs?'<h3>Logs</h3>'+pre(f.logs):''}${f.plan?'<h3>Plan JSON</h3>'+pre(f.plan):''}${f.layers?'<h3>Layer cache evidence</h3>'+table(f.layers):''}</div>`;}

export function comparisonPanel(ctx:ViewContext):string{
 const q=ctx.current,f=q.fixture??{};
 if(q.renderer==='config-editor')return `<div class="comparison-label">SUPPLIED EVIDENCE - NOT REGENERATED</div>`+configEvidence(ctx);
 if(q.renderer==='performance-investigation')return `<div class="panel-scroll"><span class="eyebrow">OBSERVED TASKS VS PLAN</span><h3>Evidence for your diagnosis</h3>${table(f.tasks??[])}<h4>Supplied physical-plan excerpt</h4>${pre(f.plan??'No plan supplied for this exercise.')}<p>Changing your answer does not produce a post-fix benchmark.</p></div>`;
 if(q.renderer==='git-visual'){const s=ctx.git();return `<div class="panel-scroll"><span class="eyebrow">WORKING / INDEX / HEAD</span><h3>State, not command matching</h3><h4>Unstaged changes</h4>${pre(gitDiff(s.index,s.files)||'Clean working tree')}<h4>Staged changes</h4>${pre(gitDiff(commitAt(s,headId(s)).tree,s.index)||'Nothing staged')}<h4>References</h4>${table([...Object.entries(s.branches).map(([ref,commit])=>({ref,commit,kind:'local'})),...Object.entries(s.tracking).map(([ref,commit])=>({ref,commit,kind:'remote-tracking'}))])}<details><summary>Goal criteria (not the command solution)</summary>${steps(q.requirements)}</details></div>`;}
 if(q.renderer==='terminal'){const t=ctx.terminal(),last=t.history.at(-1);return `<div class="panel-scroll"><span class="eyebrow">PIPELINE CONTRACT</span><h3>${t.shell==='bash'?'Text streams':'Structured objects'}</h3>${notice('Value boundary',t.shell==='bash'?'Each supported pipe passes text. Line filtering is not object property filtering.':'Supported cmdlets pass object arrays. Select-Object selects properties rather than parsing formatted columns.')}<h4>Last pipeline result</h4>${last?pre(last.output):'<p>No command yet.</p>'}<details><summary>Fixture files</summary>${Object.entries(t.files).map(([k,v])=>`<h4>${e(k)}</h4>${pre(v)}`).join('')}</details></div>`;}
 return `<div class="panel-scroll"><span class="eyebrow">DESIGN COMPARISON</span><h3>Use the same constraints for both options</h3>${f.comparison?table(f.comparison):table([{dimension:'Freshness',batch:'Scheduled / bounded intervals',stream:'Continuous processing and checkpointing'},{dimension:'Recovery',batch:'Replay a deterministic partition',stream:'Replay offsets; deduplicate and handle late data'},{dimension:'Operations',batch:'Simpler scheduling for tolerant SLAs',stream:'Additional event-time and state-management complexity'}])}${f.constraints?pre(f.constraints):''}${notice('No automatic winner','Choose from the actual latency, residency, governance, volume and team constraints. This is a reasoning reference, not a vendor cost or sizing calculator.')}</div>`;
}
