"""Deterministic authored exercise content. No scraped solution bank; all fixtures synthetic."""
from pathlib import Path
import json, sqlite3
ROOT=Path(__file__).resolve().parents[1]
refs={
 'SQL':('DuckDB SQL documentation','https://duckdb.org/docs/stable/sql/introduction'),
 'Python':('Python data structures','https://docs.python.org/3/tutorial/datastructures.html'),
 'PySpark':('Spark DataFrame API','https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/dataframe.html'),
 'pandas':('pandas group by','https://pandas.pydata.org/docs/user_guide/groupby.html'),
 'Power BI / DAX':('Microsoft DAX reference','https://learn.microsoft.com/en-us/dax/'),
 'Data modeling':('Microsoft star schema guidance','https://learn.microsoft.com/en-us/power-bi/guidance/star-schema'),
 'Airflow':('Airflow DAG concepts','https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/dags.html'),
 'Azure Data Factory':('ADF pipelines and activities','https://learn.microsoft.com/en-us/azure/data-factory/concepts-pipelines-activities'),
 'dbt':('dbt incremental models','https://docs.getdbt.com/docs/build/incremental-models'),
 'Spark performance':('Spark SQL performance tuning','https://spark.apache.org/docs/latest/sql-performance-tuning.html'),
 'OpenTofu':('OpenTofu state','https://opentofu.org/docs/language/state/'),
 'Kubernetes':('Kubernetes resource management','https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'),
 'Docker':('Docker build best practices','https://docs.docker.com/build/building/best-practices/'),
 'Bash':('GNU Bash manual','https://www.gnu.org/software/bash/manual/bash.html'),
 'PowerShell':('PowerShell pipelines','https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_pipelines'),
 'Git':('Git book: branching and merging','https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging'),
 'Cloud architecture':('Azure architecture center','https://learn.microsoft.com/en-us/azure/architecture/'),
 'Microsoft Fabric':('Fabric medallion architecture','https://learn.microsoft.com/en-us/fabric/onelake/onelake-medallion-lakehouse-architecture'),
 'Databricks':('Databricks medallion architecture','https://docs.databricks.com/aws/en/lakehouse/medallion'),
 'BigQuery':('GoogleSQL query syntax','https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax'),
}
old=[]; new=[]
def add(id,title,ws,tech,renderer,task,starter,solution,explanation,requirements,*,legacy=False,difficulty='Medium',minutes=12,fixture=None,visual=None,**extra):
 mode='execute' if renderer in ['sql-editor','code-editor'] else 'simulate' if renderer in ['dag-editor','semantic-model','terminal','git-visual'] else 'analyze' if renderer=='config-editor' else 'review'
 engine='sql' if renderer=='sql-editor' else 'python' if renderer=='code-editor' else 'dax-subset' if renderer=='semantic-model' and tech=='Power BI / DAX' else 'graph' if renderer in ['dag-editor','architecture-editor'] else 'review'
 label,url=refs.get(tech,refs['Cloud architecture'])
 q=dict(id=id,version=2 if legacy else 1,title=title,workspace=ws,topic=tech,technology=tech,difficulty=difficulty,minutes=minutes,engine=engine,language=extra.pop('language',{'sql-editor':'SQL','code-editor':'Python','pyspark-editor':'PySpark','git-visual':'Shell','terminal':tech,'config-editor':{'Docker':'Dockerfile','Kubernetes':'YAML','OpenTofu':'HCL'}.get(tech,'text'),'semantic-model':'DAX' if tech=='Power BI / DAX' else 'text','dag-editor':'JSON'}.get(renderer,'text')),summary=extra.pop('summary',task.split('. ')[0]+'.'),concept=extra.pop('concept',requirements[:2]),task=task,requirements=requirements,starter=starter,solution=solution,explanation=explanation,hints=extra.pop('hints',[requirements[0], 'State the output grain, failure boundary, or state transition before choosing a tool.']),sources=[dict(label=label,url=url)],renderer=renderer,executionMode=mode,interviewPriority='essential' if difficulty=='Easy' else 'high',followUps=extra.pop('followUps',['What changes when the input is empty, duplicated, late, or retried?','Which observation would validate your answer in a real environment?']),deepnoteLinks=[],deepnoteEmbedUrl=None,rubric=extra.pop('rubric',requirements),visual=visual or dict(type='flow',steps=['Inspect input','State the invariant','Transform or repair','Validate the result'],detail='Trace the invariant across each step. A diagram is not a substitute for execution.'),**extra)
 if fixture:q['fixture']=fixture
 (old if legacy else new).append(q)
 return q
# Preserve all 26 v1 stable identifiers, upgrading their exercise content additively.
q=add('sql-paid-revenue','Revenue without losing customers','code','SQL','sql-editor','Return customer_id, name and revenue for every customer. Sum only paid orders; customers with no paid orders must have revenue 0. Sort by customer_id.','SELECT c.customer_id, c.name,\n       0 AS revenue\nFROM customers AS c\nORDER BY c.customer_id;',"SELECT c.customer_id, c.name, COALESCE(SUM(o.amount),0) AS revenue\nFROM customers c\nLEFT JOIN orders o ON c.customer_id=o.customer_id AND o.status='paid'\nGROUP BY c.customer_id,c.name\nORDER BY c.customer_id;",'Putting paid status inside ON preserves the null-extended customer row. COALESCE turns a missing sum into zero. The output grain is one customer, not one order.',['Keep every customer.','Exclude cancelled and pending orders.','Use exact output column names and customer_id ordering.'],legacy=True,difficulty='Easy',ordered=True,dataset='retail',visual=dict(type='sql-join-trace',steps=['4 customers','LEFT JOIN paid orders','5 joined rows','GROUP BY customer','4 customer totals'],detail='Ada matches two paid orders; Cleo and Dan keep one NULL-extended row each. A WHERE filter on o.status would remove them.'))
add('sql-latest-order','The latest order, with a tie-breaker','code','SQL','sql-editor','Return customer_id, order_id and order_date for the latest order per customer. Break date ties with the greatest order_id. Sort by customer_id.',"WITH ranked AS (\n SELECT *, ROW_NUMBER() OVER (\n  PARTITION BY customer_id\n  ORDER BY order_date DESC\n ) AS rn FROM orders\n)\nSELECT customer_id,order_id,order_date\nFROM ranked WHERE rn=1 ORDER BY customer_id;", "WITH ranked AS (\n SELECT *, ROW_NUMBER() OVER (\n  PARTITION BY customer_id ORDER BY order_date DESC,order_id DESC\n ) AS rn FROM orders\n)\nSELECT customer_id,order_id,order_date FROM ranked WHERE rn=1 ORDER BY customer_id;",'ROW_NUMBER preserves every candidate while calculating rank. Filtering rn = 1 changes the grain to one row per customer. A stable tie-breaker prevents arbitrary selection.',['Partition by customer_id.','Order by descending date, then descending order_id.','Do not return customers without orders.'],legacy=True,ordered=True,dataset='retail',visual=dict(type='sql-window',steps=['Partition by customer','Order date DESC, ID DESC','Assign row numbers','Keep rn = 1'],detail='For equal dates, the greatest order_id wins. Window ORDER BY does not set final display order.'))
add('python-aggregate','Turn event rows into a dictionary','code','Python','code-editor','Implement solve(events): sum amount by country into a dictionary. Empty input returns {}. Do not mutate input.','def solve(events):\n    totals = {}\n    for event in events:\n        pass\n    return totals','def solve(events):\n    totals = {}\n    for event in events:\n        key = event["country"]\n        totals[key] = totals.get(key, 0) + event["amount"]\n    return totals','Each event is visited once: O(n) time, O(k) memory for k countries. The first occurrence needs an initial zero.',['Do not mutate input.','Include zero and negative amounts.','Use country as dictionary key.'],legacy=True,difficulty='Easy',entrypoint='solve',pythonTests=[dict(label='Two countries',args=[[dict(country='NO',amount=10),dict(country='SE',amount=5),dict(country='NO',amount=7)]],expected={'NO':17,'SE':5}),dict(label='Empty',args=[[]],expected={}),dict(label='Refund',args=[[dict(country='NO',amount=0),dict(country='NO',amount=-2)]],expected={'NO':-2})],visual=dict(type='python-data-flow',steps=['Event rows','Read country key','get(key, 0) + amount','Dictionary of totals'],detail='A list contains events; a dictionary indexes their accumulated totals.'))
add('python-two-sum','Find the matching pair','code','Python','code-editor','Implement solve(numbers,target). Return increasing indices of the only valid pair, or [] when none exists. Do not reuse an index.','def solve(numbers, target):\n    seen = {}\n    for index, value in enumerate(numbers):\n        pass\n    return []','def solve(numbers, target):\n    seen = {}\n    for index, value in enumerate(numbers):\n        other = target - value\n        if other in seen:\n            return [seen[other], index]\n        seen[value] = index\n    return []','Check the complement before inserting the current number. That permits duplicate values at different indices without reusing one element.',['Distinct indices.','Handle duplicate and negative values.','Aim for one pass.'],legacy=True,difficulty='Easy',entrypoint='solve',pythonTests=[dict(label='Pair',args=[[2,7,11,15],9],expected=[0,1]),dict(label='Duplicate',args=[[3,3],6],expected=[0,1]),dict(label='Negative',args=[[-2,5,3],1],expected=[0,2]),dict(label='No match',args=[[1,2],10],expected=[])])
spark_events=[dict(customer_id=1,event_time='2026-01-02',event_id=101,amount=10),dict(customer_id=1,event_time='2026-01-02',event_id=102,amount=15),dict(customer_id=2,event_time='2026-01-01',event_id=103,amount=7)]
spark_fixture={'tables':{'events':spark_events},'schema':'customer_id: long, event_time: string, event_id: long, amount: double','expected':[spark_events[1],spark_events[2]],'plan':'Scan events\n  Exchange hashpartitioning(customer_id)\n    Sort customer_id, event_time DESC, event_id DESC\n      Window row_number\n        Filter rn = 1\n          Project (drop rn)','planNotice':'Illustrative plan, not captured from a running Spark session.'}
add('spark-dedup','Deduplicate events deterministically','code','PySpark','pyspark-editor','Keep the latest event per customer, breaking event_time ties by descending event_id. Explain why dropDuplicates(["customer_id"]) does not express this rule.','from pyspark.sql import functions as F, Window\n\nw = Window.partitionBy("customer_id")\n# Add order, row_number, filter and drop.', 'from pyspark.sql import functions as F, Window\n\nw = Window.partitionBy("customer_id").orderBy(\n    F.col("event_time").desc(), F.col("event_id").desc()\n)\nresult = (events.withColumn("rn", F.row_number().over(w))\n          .filter(F.col("rn") == 1).drop("rn"))','A DataFrame has no implicit reliable row order. The window expresses a deterministic business rule but generally needs redistribution and sorting. This page never executes Spark.',['Partition by customer_id.','Both ordering columns descending.','Keep rn = 1 and remove the helper.'],legacy=True,fixture=spark_fixture,visual=dict(type='pyspark-transformations',steps=['3 input events','Exchange by customer','Sort within partition','Window row_number','2 latest events'],detail='Exchange is a shuffle boundary. SQL ROW_NUMBER and this PySpark window express the same latest-record rule.'))
add('tsql-running-total','A running total in T-SQL','code','T-SQL','sql-editor','Write a T-SQL running_amount by customer with order_date and order_id ordering. Explain ROWS versus RANGE peers. This is dialect review, not DuckDB execution.','SELECT order_id, customer_id,\n SUM(amount) OVER (\n  PARTITION BY customer_id\n  -- ordering and frame\n ) AS running_amount\nFROM orders;', 'SELECT order_id, customer_id,\n SUM(amount) OVER (\n  PARTITION BY customer_id ORDER BY order_date, order_id\n  ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n ) AS running_amount\nFROM orders;','ROWS counts physical rows in the declared order. RANGE uses value peers; duplicated dates can extend the frame together. A stable ordering key makes row-by-row intent explicit.',['Partition by customer.','Use an explicit ROWS frame.','Discuss duplicate dates.'],legacy=True,language='T-SQL',visual=dict(type='sql-window',steps=['Customer partition','Date + ID order','ROWS frame','Cumulative SUM'],detail='The final SELECT display order is separate from the window order.'))['engine']='review'
add('bigquery-qualify','Latest events with QUALIFY','code','BigQuery','sql-editor','Select the latest event per customer from analytics.events using QUALIFY. State whether latest means all time or inside a date range.','SELECT *\nFROM `analytics.events`\nQUALIFY -- window condition', 'SELECT *\nFROM `analytics.events`\nQUALIFY ROW_NUMBER() OVER (\n PARTITION BY customer_id ORDER BY event_time DESC,event_id DESC\n) = 1;','QUALIFY filters window results. A WHERE date filter changes candidate rows before ranking; do not introduce one without clarifying the business scope.',['ROW_NUMBER with QUALIFY.','Deterministic tie-breaker.','State date scope.'],legacy=True,language='BigQuery SQL')['engine']='review'
add('pandas-grain','Group a DataFrame without losing its meaning','code','pandas','code-editor','Implement solve(rows): construct a DataFrame and return records with customer_id, total_amount, line_count, sorted by customer_id. Count rows including missing amounts. Empty input returns [].','def solve(rows):\n    import pandas as pd\n    if not rows:\n        return []\n    lines = pd.DataFrame(rows)\n    # Named aggregation, then to_dict("records")\n    return []', 'def solve(rows):\n    import pandas as pd\n    if not rows:\n        return []\n    lines = pd.DataFrame(rows)\n    return (lines.groupby("customer_id", as_index=False)\n            .agg(total_amount=("amount", "sum"),\n                 line_count=("amount", "size"))\n            .sort_values("customer_id").to_dict("records"))','size counts rows while count excludes null values in the chosen column. This exercise has non-null customer IDs; discuss dropna=False separately for missing keys.',['One row per customer.','Sum amount; size for row count.','Return JSON-compatible records.'],legacy=True,difficulty='Easy',entrypoint='solve',pythonTests=[dict(label='Null amount counts as a row',args=[[dict(customer_id=1,amount=10),dict(customer_id=1,amount=None),dict(customer_id=2,amount=7)]],expected=[dict(customer_id=1,total_amount=10,line_count=2),dict(customer_id=2,total_amount=7,line_count=1)]),dict(label='Empty input',args=[[]],expected=[])],fixture={'packages':['pandas']})
add('git-safe-undo','Undo a shared commit safely','code','Git','concept-case','A bad commit is already on a shared branch. Describe a safe inspection and undo sequence without rewriting shared history.','git status\n# Inspect and safely undo the shared commit','git status\ngit show abc123\ngit revert abc123\ngit log --oneline -3\n# Review, test, then push under team policy.','Revert adds an inverse commit; reset moves a ref. Revert may still conflict, so inspect and test. This original case remains a review; the new Git visual cases execute only a simulation.',['Inspect status.','Use revert for shared history.','Do not default to force push.'],legacy=True,difficulty='Easy')
add('linux-log-triage','Find failures in a pipeline log','code','Bash','terminal','Show the last 20 case-insensitive error occurrences in pipeline.log with line numbers. Leave the file unchanged. Type commands in the virtual terminal.','',"grep -in 'error' pipeline.log | tail -n 20",'Filter first, then take the last matching lines. Real grep returns 1 for no matches; this bounded virtual terminal displays empty output and does not emulate every POSIX exit status.',['Case-insensitive matching.','Include line numbers.','Keep the file unchanged.'],legacy=True,difficulty='Easy',fixture={'shell':'bash','goal':'log-errors'})
add('bi-star-schema','Design the sales star schema','model','Data modeling','semantic-model','Choose the Sales fact grain and inspect dimension relationships. Sales contains one row per order line, not per order.','Model notes:\nGrain:\nDimension keys:\nFilter direction:', 'Grain: order-line\nDimCustomer[CustomerKey] 1 -> * Sales[CustomerKey]\nDimProduct[ProductKey] 1 -> * Sales[ProductKey]\nUse single-direction dimension-to-fact filtering.','An order can have several lines. Joining facts at different grains can multiply totals. Validate uniqueness on the one side before using a relationship.',['Choose order-line grain.','Activate both dimension-to-Sales relationships.','Check dimension-key uniqueness.'],legacy=True,difficulty='Easy',template='model',expectedGrain='order-line',visual=dict(type='filter-propagation',steps=['Country slicer','DimCustomer keys','Active 1:* relationship','Visible Sales rows','Revenue measure'],detail='An inactive relationship stops propagation in this teaching model.'))
for id,title,task,starter,solution,explanation in [
 ('bi-revenue','Write a revenue measure','Write Revenue as quantity times unit price over visible Sales rows. Compare All countries with Norway.','Revenue = SUM(Sales[UnitPrice])','Revenue = SUMX(Sales, Sales[Quantity] * Sales[UnitPrice])','SUMX evaluates the row multiplication before aggregation. The country and category filters limit the iterator input.'),
 ('bi-margin','Gross margin that handles zero revenue','Write Margin using [Gross Profit] and [Revenue]. Select Denmark to check the empty filter context.','Margin = [Gross Profit] / [Revenue]','Margin = DIVIDE([Gross Profit], [Revenue])','DIVIDE returns BLANK when the denominator is zero or blank by default. This is a ratio of sums, not a mean of individual margins.'),
 ('bi-filter-context','Replace a country filter with CALCULATE','Write Norway Revenue. Set the country slicer to Sweden and explain filter replacement.','Norway Revenue = CALCULATE(\n [Revenue]\n -- country filter\n)','Norway Revenue = CALCULATE([Revenue], DimCustomer[Country] = "Norway")','A same-column equality in CALCULATE replaces the existing country filter. Unrelated category filters remain. Context transition inside iterators is deliberately unsupported.')]:
 add(id,title,'model','Power BI / DAX','semantic-model',task,starter,solution,explanation,['Use the named measure formula.','Inspect active dimension relationships.','Try an empty country selection.'],legacy=True,difficulty='Easy' if id=='bi-revenue' else 'Medium',template='model',visual=dict(type='filter-propagation',steps=['Slicer context','Relationship propagation','Visible fact rows','Evaluate measure'],detail=explanation))
add('bi-csharp','Organize measures with a C# script','model','C# / Tabular Editor','concept-case','Put only selected measures in the Revenue display folder. Explain how to review the selection and save a model backup.','foreach (var measure in Selected.Measures)\n{\n    // Set the display folder\n}', 'foreach (var measure in Selected.Measures)\n{\n    measure.DisplayFolder = "Revenue";\n}', 'Selected.Measures limits the edit scope. This page does not run .NET, connect to XMLA, or modify a Power BI model.',['Iterate selected measures only.','Set DisplayFolder.','Review changes on a copy.'],legacy=True,difficulty='Easy',language='C#')
scd={'tables':{'DimCustomerVersion':[dict(VersionKey=10,CustomerId=1,Country='Switzerland',ValidFrom='2025-01-01',ValidTo='2026-01-01'),dict(VersionKey=11,CustomerId=1,Country='Norway',ValidFrom='2026-01-01',ValidTo='9999-12-31')],'Sales':[dict(SaleKey=1,CustomerId=1,EventDate='2025-12-31',Revenue=100),dict(SaleKey=2,CustomerId=1,EventDate='2026-01-01',Revenue=80)]},'expected':[dict(SaleKey=1,VersionKey=10),dict(SaleKey=2,VersionKey=11)]}
add('bi-scd','Preserve customer history with SCD Type 2','model','Data modeling','concept-case','A customer changes country. Design version keys and an event-time lookup. Explain where a late fact for December belongs.','DimCustomerVersion\n- CustomerVersionKey\n- CustomerBusinessKey\n- Country\n# Add validity fields and lookup rule','Use one surrogate key per version, ValidFrom, ValidTo and IsCurrent.\nLookup: ValidFrom <= event_date AND event_date < ValidTo.\nStore the resolved version key in the fact.\nDefine an unknown-member and late-arrival policy.','Exclusive upper bounds avoid overlapping adjacent versions. A late December fact still resolves to the historical country, not the current row.',['Surrogate key per version.','Non-overlapping half-open validity ranges.','Event-time lookup for late facts.'],legacy=True,fixture=scd,visual=dict(type='scd-timeline',steps=['Version 10: CH through 2025','Boundary: 2026-01-01','Version 11: NO from 2026'],detail='2025-12-31 -> key 10; 2026-01-01 -> key 11. ValidTo is exclusive.'))
for id,title,tech,template,task,solution,explanation in [
 ('dag-data-quality','Put quality checks before publication','Airflow','pipeline','Remove the transform-to-publish bypass. Connect quality to publish. Run with zero retries, then allow quality one retry.','extract -> transform -> quality -> publish; quality.retries = 1','With all_success, a failed quality gate blocks publication. A retry recovers the fixture failure, but cannot repair non-idempotent writes.'),
 ('adf-watermark','Advance a watermark only after success','Azure Data Factory','watermark','Make persist_watermark depend on successful validate, not just copy. Explain replay when copying succeeds but watermark persistence fails.','read_watermark -> copy -> validate -> persist_watermark\nThe persist edge condition must be Succeeded.','Capture a high watermark, load a bounded interval and advance only after successful validation. A retry must be idempotent; a watermark alone is not exactly once.'),
 ('dbt-lineage','Test the model before its consumer','dbt','dbt','Repair the quality-to-mart dependency. Write a customer-grain mart with ref("stg_orders"). Explain unique and not-null tests.','SELECT customer_id, SUM(amount) AS revenue\nFROM {{ ref("stg_orders") }}\nGROUP BY customer_id','ref records a dependency. The quality-gate simulator is an explicit abstraction, not dbt build test-selection semantics.')]:
 add(id,title,'pipeline',tech,'dag-editor',task,'# Use Graph and its synchronized JSON config.\n# Add implementation notes here.',solution,explanation,['Remove the direct quality bypass.','Keep the dependency graph acyclic.','Explain retry and failure propagation.'],legacy=True,difficulty='Easy' if tech!='Azure Data Factory' else 'Medium',template=template,visual=dict(type='dag',steps=['Bounded input','Transform / copy','Quality gate','Publish / advance watermark'],detail=explanation))
add('dag-idempotency','Rerun a daily partition safely','pipeline','Airflow','concept-case','A daily task appends the full day on every retry. Propose a partition-replacement or key-based merge strategy that also supports a backfill.','def load_sales(processing_date):\n    # bounded read and retry-safe write\n    pass','Read the explicit interval. Write to staging and validate. Atomically replace the destination partition when supported, or merge a deduplicated source on a stable key. Retry the same interval without new business keys.','Idempotency is a property of the full read/write design. Retrying an unconditional append does not make it safe.',['Explicit data interval, not only now().','Stable keys or atomic partition replacement.','Partial-failure recovery.'],legacy=True)
for id,title,tech,template,chain,task,explanation in [
 ('arch-fabric','Design a Fabric analytics path','Microsoft Fabric','fabric','source[Operational source] -> ingest[Fabric pipeline]\ningest -> store[OneLake lakehouse]\nstore -> semantic[Semantic model]\nsemantic -> report[Power BI report]','Create an ingestion-to-report path. Explain freshness, a quality boundary, access permissions and the semantic layer.','A structural check confirms connected roles, not licensing, security or refresh guarantees.'),
 ('arch-databricks','A small medallion pipeline','Databricks','databricks','source[Events] -> bronze[Bronze raw]\nbronze -> silver[Silver validated]\nsilver -> gold[Gold revenue]\ngold -> report[BI consumer]','Preserve replayable raw inputs, deduplicate at a defined business grain and publish a business-ready aggregate.','Bronze, silver and gold express quality and consumption responsibilities, not merely folders.'),
 ('arch-bigquery','A partition-aware BigQuery design','BigQuery','bigquery','source[Application events] -> ingest[Batch ingestion]\ningest -> warehouse[BigQuery tables]\nwarehouse -> transform[Curated SQL models]\ntransform -> report[Dashboard]','Explain the common query access pattern, choose a date partition and clustering key, and state what scan metric to verify.','Partition pruning follows suitable filters. Clustering can reduce blocks scanned but does not guarantee a fixed cost reduction.')]:
 add(id,title,'architecture',tech,'architecture-editor',task,chain,chain,explanation,['Connect the end-to-end data path.','State freshness and access assumptions.','Justify the serving grain and validation boundary.'],legacy=True,difficulty='Easy',template=template)
add('arch-tofu','Keep state and secrets out of the wrong places','architecture','OpenTofu','concept-case','Explain init, validate, plan, review and apply. Propose protected remote state and locking; explain why secrets do not belong in committed tfvars.','terraform {\n  # Describe backend requirements\n}', 'tofu init\ntofu validate\ntofu plan -out=reviewed.plan\n# Review and approve separately\ntofu apply reviewed.plan\n# Protected backend, least privilege, locking and recovery.','State can contain sensitive values. Locking prevents simultaneous writers where supported; it does not replace recovery or access controls.',['Separate config from state.','Review a saved plan before apply.','Protect state and keep secrets out of version control.'],legacy=True,language='HCL')
k8fixture={'tabs':['Object graph','Events','Logs'],'graph':{'nodes':[{'id':'deployment','label':'Deployment: worker','role':'controller','x':30,'y':40},{'id':'replicaset','label':'ReplicaSet','role':'controller','x':260,'y':40},{'id':'pod','label':'Pod: worker-7','role':'OOMKilled','x':490,'y':40}], 'edges':[{'id':'a','from':'deployment','to':'replicaset'},{'id':'b','from':'replicaset','to':'pod'}]},'events':[{'reason':'BackOff','message':'Back-off restarting failed container','count':7},{'reason':'OOMKilled','message':'Last termination exit code 137','count':1}], 'logs':'09:02 INFO batch_size=100000 rows=100000\n09:02 INFO rss=418Mi\n09:02 process terminated; previous instance OOMKilled\n','workingSetMi':400,'checks':[{'label':'Memory limit exceeds measured working set','kind':'memory-limit','min':400},{'label':'Memory request is explicit','pattern':'requests:[\\s\\S]*?memory:'}]}
add('arch-kubernetes','Diagnose an OOMKilled data worker','architecture','Kubernetes','config-editor','The worker has a 256Mi limit and a measured working set around 400Mi. Repair the resource settings and explain batch size, concurrency and memory-growth checks.','resources:\n  requests:\n    cpu: "250m"\n    memory: "128Mi"\n  limits:\n    memory: "256Mi"','resources:\n  requests:\n    cpu: "250m"\n    memory: "512Mi"\n  limits:\n    memory: "768Mi"\n# Illustrative headroom; verify node capacity and sustained usage.','Requests guide scheduling, while a memory limit can cause termination. Readiness does not fix memory growth. The events and logs are fixtures, not a real cluster.',['Distinguish request from limit.','Use measured headroom, not unlimited memory.','Investigate batch size, concurrency and leaks.'],legacy=True,fixture=k8fixture)
perf={'metrics':{'Input':'480 GB','Rows':'2.4 billion','Files':'28,000','Partitions':'200','Median task':'7 s','Slowest task':'96 s','Shuffle read':'390 GB','Shuffle write':'420 GB','Spill':'85 GB','Largest partition':'18.2 GB','Median partition':'1.7 GB','Executors':'8 x 4 cores','Memory/executor':'12 GB','fact_sales':'470 GB','dim_country':'4 MB','Join strategy':'SortMergeJoin'},'tasks':[{'task':i,'duration_s':x,'read_GB':18.2 if x==96 else round(.8+i*.15,2),'spill_GB':13.2 if x==96 else 0} for i,x in enumerate([5,6,7,7,8,6,96,7],1)],'plan':'Scan fact_sales (partition filter missing)\nExchange hashpartitioning(country_id, 200)\nSortMergeJoin [country_id]\n  Scan dim_country (4 MB)\nHashAggregate [country_id]','diagnoses':[{'id':'skew','label':'Investigate skew / a hot key','correct':True},{'id':'broadcast','label':'Evaluate broadcasting the 4 MB dimension','correct':True},{'id':'files','label':'Investigate excessive file count / scan overhead','correct':True},{'id':'leak','label':'The evidence proves a memory leak','correct':False},{'id':'promise','label':'Doubling executors guarantees half the time','correct':False}]}
add('arch-spark-skew','Explain the slow task in a Spark stage','architecture','Spark performance','performance-investigation','Inspect the stage evidence. Select diagnoses supported by the fixture, explain the hot task, and propose what to validate before changing join strategy.','# Record diagnosis and next measurement.','The 96s task versus 7s median and 18.2GB largest partition support a skew investigation. Evaluate the 4MB dimension for broadcast, inspect output cardinality, and check scan pruning / files. Validate the physical plan and memory use; do not promise runtime.','These are deterministic teaching metrics, not measured in this app. Skew can persist after increasing partition count because one hot key remains together.',['Use task and partition evidence.','Check broadcast memory and join correctness.','Do not infer exact runtime or prove a leak.'],legacy=True,difficulty='Hard',fixture=perf,template='spark',visual=dict(type='spark-stage',steps=['Scan 480 GB','Shuffle 390 GB read','One hot task: 96 s','Aggregate','Write'],detail='The maximum task controls the straggler tail; a median alone hides it.'))
add('arch-table-formats','What does a lakehouse snapshot remember?','architecture','Cloud architecture','architecture-editor','Separate query engine, catalog metadata and Parquet files. Explain consistent snapshots and why a table format does not create a Spark cluster.','engine[Query engine] -> catalog[Catalog / metadata]\ncatalog -> files[Parquet files]','engine[Query engine] -> catalog[Catalog / committed snapshot]\ncatalog -> files[Referenced Parquet files]','A reader resolves a committed snapshot rather than blindly listing every file. Compute, catalog and storage have distinct responsibilities.',['Separate compute, storage and metadata.','Describe consistent snapshot selection.','No managed-cluster assumption.'],legacy=True,difficulty='Easy',template='lakehouse')
# Representative V2 additions: quality rather than a large generated question bank.
add('v2-sql-quality','Detect duplicate keys before a merge','code','SQL','sql-editor','Return customer_id and duplicate_count for customer IDs appearing more than once in orders. Sort by customer_id.','SELECT customer_id\nFROM orders\n-- Group and filter duplicate keys', 'SELECT customer_id, COUNT(*) AS duplicate_count\nFROM orders GROUP BY customer_id HAVING COUNT(*) > 1\nORDER BY customer_id;', 'GROUP BY changes row grain. HAVING filters groups after aggregation. A MERGE source may need deterministic deduplication, not just detection.',['Use COUNT(*) not COUNT(amount).','Filter groups with more than one row.','State the source grain.'],difficulty='Easy',ordered=True,dataset='retail')
add('v2-sql-cte','Customers above average paid spend','code','SQL','sql-editor','Return customer_id and revenue for customers whose paid total exceeds the average of paid totals among customers with at least one paid order. Sort by customer_id.','WITH totals AS (\n -- paid total per customer\n)\nSELECT * FROM totals;',"WITH totals AS (\n SELECT customer_id, SUM(amount) AS revenue\n FROM orders WHERE status='paid' GROUP BY customer_id\n)\nSELECT customer_id,revenue FROM totals\nWHERE revenue > (SELECT AVG(revenue) FROM totals)\nORDER BY customer_id;",'Compute the average at the customer-total grain, not the raw order grain. Customers without paid orders are excluded from this specifically defined average.',['Filter paid orders before grouping.','Average customer totals, not order amounts.','Do not silently include zero-spend customers.'],ordered=True,dataset='retail')
add('v2-python-batches','Batch records without losing the final chunk','code','Python','code-editor','Implement solve(records,size). Return batches as lists. A final short batch must be kept; size <= 0 raises ValueError (tested separately in explanation).','def solve(records, size):\n    # Validate size and return batches\n    return []','def solve(records, size):\n    if size <= 0:\n        raise ValueError("size must be positive")\n    return [records[i:i + size] for i in range(0, len(records), size)]','Slice boundaries naturally keep the short final batch. A generator variant can reduce retained output memory but does not by itself make a materialized source streaming.',['Keep the final short batch.','Do not mutate records.','Handle empty input.'],difficulty='Easy',entrypoint='solve',pythonTests=[dict(label='Remainder',args=[[1,2,3,4,5],2],expected=[[1,2],[3,4],[5]]),dict(label='Empty',args=[[],3],expected=[]),dict(label='One large batch',args=[[1,2],9],expected=[[1,2]])])
add('v2-python-latest','Latest revision from API records','code','Python','code-editor','Implement solve(records). Keep the highest revision for each id and return records sorted by id. Equal revisions keep the first record.','def solve(records):\n    latest = {}\n    # Key by id; compare revision\n    return []','def solve(records):\n    latest = {}\n    for row in records:\n        old = latest.get(row["id"])\n        if old is None or row["revision"] > old["revision"]:\n            latest[row["id"]] = row\n    return [latest[k] for k in sorted(latest)]','A dictionary stores one candidate per key. Using > rather than >= makes the tie policy explicit. Return records without mutating input.',['One record per id.','Highest revision wins.','First wins equal revisions.'],entrypoint='solve',pythonTests=[dict(label='Out of order',args=[[dict(id=2,revision=1),dict(id=1,revision=2),dict(id=1,revision=1)]],expected=[dict(id=1,revision=2),dict(id=2,revision=1)]),dict(label='Stable tie',args=[[dict(id=1,revision=1,value='first'),dict(id=1,revision=1,value='second')]],expected=[dict(id=1,revision=1,value='first')]),dict(label='Empty',args=[[]],expected=[])])
add('v2-spark-aggregate','Revenue and event count in PySpark','code','PySpark','pyspark-editor','Build result with customer_id, revenue and event_count from events. Use built-in aggregations; count rows even when amount is null.','from pyspark.sql import functions as F\n\nresult = (events\n    .groupBy("customer_id")\n    # Add named aggregates\n)', 'from pyspark.sql import functions as F\nresult = (events.groupBy("customer_id")\n .agg(F.sum("amount").alias("revenue"),\n      F.count("*").alias("event_count")))','groupBy causes an aggregation shuffle unless compatible partitioning already satisfies the plan. count("*") counts rows; count("amount") excludes null amounts. This is review, never browser Spark execution.',['Group by customer_id.','Built-in sum, not Python UDF.','Count all rows.'],difficulty='Easy',fixture={**spark_fixture,'expected':[dict(customer_id=1,revenue=25,event_count=2),dict(customer_id=2,revenue=7,event_count=1)],'plan':'Scan -> partial HashAggregate -> Exchange customer_id -> final HashAggregate'},visual=dict(type='pyspark-transformations',steps=['3 events','Partial aggregate','Exchange by key','Final aggregate','2 customers'],detail='Built-in aggregations expose the work to the Spark optimizer.'))
add('v2-spark-join','A left join that preserves unmatched facts','code','PySpark','pyspark-editor','Enrich events with a small customer dimension by customer_id. Keep unmatched events and explain why duplicate dimension keys would multiply facts.','from pyspark.sql import functions as F\n\n# Enrich events using customers', 'result = events.join(F.broadcast(customers), "customer_id", "left")\n# Validate customer_id uniqueness in customers before trusting row counts.', 'Broadcasting is a plan choice, not a correctness guarantee. The dimension must fit broadcast memory and have the intended key uniqueness. A left join preserves facts but can still multiply them.',['Left join, not inner.','Check dimension uniqueness.','Validate size before broadcasting.'],fixture={**spark_fixture,'tables':{'events':spark_events,'customers':[dict(customer_id=1,country='NO')]},'expected':[{**r,'country':'NO' if r['customer_id']==1 else None} for r in spark_events],'plan':'Illustrative: Scan events -> BroadcastHashJoin LeftOuter <- BroadcastExchange customers'},visual=dict(type='sql-join-trace',steps=['3 facts','1 unique dimension key','Left broadcast join','3 enriched facts'],detail='An inner join would drop customer 2; duplicate dimension keys would multiply customer 1 events.'))
add('v2-airflow-branch','Join after a skipped branch','pipeline','Airflow','dag-editor','The optional branch is skipped. Configure the final join so that it runs when at least one parent succeeds and none failed. Compare all_success and none_failed_min_one_success.','# Use synchronized graph/config for trigger rules.','Set join.triggerRule to none_failed_min_one_success. Do not use all_done when a failed prerequisite must block publication.','A skipped branch is not a failure, but all_success will not accept it. none_failed_min_one_success encodes the desired condition.',['Require at least one successful parent.','Block actual failures.','Do not treat skipped as success.'],fixture={'graph':{'nodes':[{'id':'extract','label':'Extract','role':'task','x':30,'y':40},{'id':'required','label':'Required branch','role':'task','x':260,'y':40},{'id':'optional','label':'Optional branch','role':'task','x':260,'y':190,'skip':True},{'id':'join','label':'Publish join','role':'task','x':490,'y':100,'triggerRule':'all_success'}],'edges':[{'id':'e1','from':'extract','to':'required'},{'id':'e2','from':'extract','to':'optional'},{'id':'e3','from':'required','to':'join'},{'id':'e4','from':'optional','to':'join'}]},'targetTask':'join'})
add('v2-dbt-failure','Follow a failing dbt build artifact','pipeline','dbt','pipeline-investigation','A uniqueness test on stg_orders failed. Inspect the artifact-shaped fixtures and explain why revenue must not be published. Repair the SQL deduplication approach in your answer.','WITH ranked AS (\n SELECT *, ROW_NUMBER() OVER (\n  PARTITION BY order_id ORDER BY updated_at DESC, ingestion_id DESC\n ) AS rn\n FROM {{ source("raw", "orders") }}\n)\n-- Keep one deterministic row', 'SELECT * EXCLUDE(rn) FROM ranked WHERE rn = 1;\n-- Then rerun unique/not_null tests and validate fact grain before publication.', 'A failed test needs an investigation into source grain and change semantics. Silently dropping duplicates can hide upstream contract errors. These fixtures do not compile Jinja or execute dbt.',['Identify the failing node.','Trace affected downstream consumers.','State a deterministic latest-record and test policy.'],fixture={'manifest':{'metadata':{'dbt_schema_version':'https://schemas.getdbt.com/dbt/manifest/v12.json','note':'Curated subset, not a full manifest'},'nodes':{'model.demo.stg_orders':{'resource_type':'model','depends_on':{'nodes':['source.demo.raw.orders']},'config':{'materialized':'view'}},'test.demo.unique_stg_orders':{'resource_type':'test','depends_on':{'nodes':['model.demo.stg_orders']}},'model.demo.fct_revenue':{'resource_type':'model','depends_on':{'nodes':['model.demo.stg_orders']},'config':{'materialized':'incremental','unique_key':'customer_id'}}}},'run_results':{'results':[{'unique_id':'model.demo.stg_orders','status':'success','execution_time':1.2},{'unique_id':'test.demo.unique_stg_orders','status':'fail','failures':2},{'unique_id':'model.demo.fct_revenue','status':'skipped','execution_time':0}]},'graph':{'nodes':[{'id':'raw','label':'raw.orders','role':'source','x':30,'y':40},{'id':'staging','label':'stg_orders','role':'model','x':260,'y':40},{'id':'test','label':'unique(order_id)','role':'test fail: 2','x':490,'y':40},{'id':'mart','label':'fct_revenue','role':'skipped','x':260,'y':190}],'edges':[{'id':'a','from':'raw','to':'staging'},{'id':'b','from':'staging','to':'test'},{'id':'c','from':'staging','to':'mart'}]}})
add('v2-spark-files','Small files without a fake speed estimate','architecture','Spark performance','performance-investigation','Inspect this file-heavy stage. Distinguish scheduling and file-open overhead from a skew claim. Explain a compaction plan and how to measure improvement.','# Diagnosis and measurement plan','Many tiny files and comparable task durations suggest investigating file/listing overhead. Compact to a workload-appropriate file size and measure metadata time, scan tasks and bytes. Avoid promising a universal target size or exact speedup.','The absence of a long task tail weakens a skew diagnosis here. File layout choices depend on write frequency, downstream queries and partition pruning.',['Use file and task evidence.','Do not claim skew without a distribution.','Measure scan overhead before and after.'],fixture={'metrics':{'Input':'8 GB','Files':'80,000','Median file':'100 KB','Tasks':'80,000','Median task':'0.6 s','Slowest task':'0.9 s','Spill':'0 GB','Scheduler delay':'Fixture indicates high overhead'},'tasks':[dict(task=i,duration_s=.5+i*.04,read_GB=.0001,spill_GB=0) for i in range(1,9)],'plan':'FileScan parquet [date partition] -> Project -> Write','diagnoses':[{'id':'files','label':'Investigate small-file and scheduling overhead','correct':True},{'id':'compact','label':'Evaluate compaction and measure scan overhead','correct':True},{'id':'skew','label':'The evidence proves a hot-key skew problem','correct':False}]})
add('v2-tofu-replacement','Review a destructive replacement plan','architecture','OpenTofu','config-editor','The plan fixture replaces a storage bucket after a name change. Identify delete/create, explain state implications, and add a prevent_destroy safeguard to the example HCL.','resource "aws_s3_bucket" "lake" {\n  bucket = "analytics-lake-v2"\n}', 'resource "aws_s3_bucket" "lake" {\n  bucket = "analytics-lake-v2"\n  lifecycle { prevent_destroy = true }\n}\n# Investigate a migration rather than blindly applying replacement.', 'prevent_destroy blocks destructive plans while the configuration remains applicable; it is not a backup. The plan is a fixed JSON fixture and is not recomputed when you edit HCL.',['Identify delete/create replacement.','Do not run apply.','Protect data and design migration.'],fixture={'plan':{'format_version':'1.2','resource_changes':[{'address':'aws_s3_bucket.lake','change':{'actions':['delete','create'],'before':{'bucket':'analytics-lake-v1'},'after':{'bucket':'analytics-lake-v2'},'replace_paths':[['bucket']]}}]},'checks':[{'label':'Destruction safeguard is explicit','pattern':'prevent_destroy\\s*=\\s*true'}],'graph':{'nodes':[{'id':'bucket','label':'Bucket replacement','role':'delete + create','x':30,'y':60},{'id':'policy','label':'Access policy','role':'dependent','x':270,'y':60}],'edges':[{'id':'e','from':'bucket','to':'policy'}]}})
add('v2-k8-selector','Why does the Service have no endpoints?','architecture','Kubernetes','config-editor','The Pod template has app: worker, but the Service selects app: api. Repair the selector and describe readiness and port checks.','apiVersion: v1\nkind: Service\nmetadata:\n  name: worker\nspec:\n  selector:\n    app: api\n  ports:\n    - port: 80\n      targetPort: 8080', 'apiVersion: v1\nkind: Service\nmetadata:\n  name: worker\nspec:\n  selector:\n    app: worker\n  ports:\n    - port: 80\n      targetPort: 8080', 'The selector must match pod labels, not merely the Deployment name. Readiness and targetPort must also be checked. This analyzer inspects the fixture pattern, not a Kubernetes API.',['Match app: worker.','Keep targetPort 8080 for the fixture.','Explain readiness separately.'],fixture={'events':[{'reason':'NoEndpoints','message':'Service selector app=api matches 0 pods'},{'reason':'PodReady','message':'worker-7 labels app=worker, port 8080'}],'logs':'worker-7: listening on 0.0.0.0:8080\nreadiness: ok\n','checks':[{'label':'Selector matches the Pod label','pattern':'selector:\\s*\\n\\s*app:\\s*worker'},{'label':'Target port matches listening process','pattern':'targetPort:\\s*8080'}]})
add('v2-docker-cache','Stop reinstalling dependencies for every edit','architecture','Docker','config-editor','The Dockerfile copies all source before installing requirements. Reorder layers for reuse and run the final container as non-root.','FROM python:3.12-slim\nWORKDIR /app\nCOPY . .\nRUN pip install --no-cache-dir -r requirements.txt\nCMD ["python", "pipeline.py"]','FROM python:3.12-slim\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\nCOPY . .\nUSER 10001\nCMD ["python", "pipeline.py"]','Separating the dependency manifest from frequently edited source preserves the install layer when only application code changes. Exclude secrets and irrelevant files using .dockerignore; non-root permissions still need testing.',['Copy requirements before pip install.','Copy changing source after dependency installation.','Use a non-root user.'],fixture={'layers':[{'layer':'FROM python:3.12-slim','invalidated':'Only when base changes'},{'layer':'COPY . .','invalidated':'Any source edit'},{'layer':'RUN pip install','invalidated':'Also invalidated by earlier source copy'}],'checks':[{'label':'Cache-friendly dependency ordering','kind':'docker-order'},{'label':'Non-root user','pattern':'USER\\s+(?!root\\b|0\\b)\\S+'}]},visual=dict(type='docker-layers',steps=['Base image','COPY requirements','Install dependencies','COPY application','Non-root runtime'],detail='A changed layer invalidates subsequent cached layers. Keep frequently changing input later.'))
add('v2-bash-csv','Count paid rows in a CSV fixture','architecture','Bash','terminal','Count paid CSV rows by country without modifying sales.csv. The fixture has simple unquoted country/amount/status fields. General CSV parsing needs a CSV-aware tool.','',"cat data/sales.csv | grep ',paid' | cut -d, -f1 | sort | uniq -c",'Filter paid rows, extract country, sort adjacent equal keys and count them. This text pipeline is safe for this simple fixture, not arbitrary quoted CSV.',['Exclude the header and non-paid rows.','Group adjacent country names before uniq.','Know when text tools are unsafe for CSV.'],difficulty='Easy',fixture={'shell':'bash','goal':'paid-country'})
add('v2-powershell-csv','Filter CSV objects, not text fragments','architecture','PowerShell','terminal','Import sales.csv, keep status paid, and select country and amount. Inspect the output type. Do not use Bash grep as a substitute.','', 'Import-Csv data/sales.csv | Where-Object { $_.status -eq "paid" } | Select-Object country,amount', 'Import-Csv yields objects with named string properties. Where-Object filters those objects and Select-Object shapes properties. Numeric comparisons should use explicit casts when needed.',['Use Import-Csv.','Filter the status property.','Keep object records through Select-Object.'],difficulty='Easy',fixture={'shell':'powershell','goal':'paid-objects'})
add('v2-powershell-json','Expand an API array and keep active records','architecture','PowerShell','terminal','Read data/api.json, parse JSON, expand items, and keep active objects. No network request is needed.','', 'Get-Content data/api.json | ConvertFrom-Json | Select-Object -ExpandProperty items | Where-Object { $_.status -eq "active" }', 'JSON parsing creates properties and arrays. ExpandProperty turns the items array into the pipeline sequence, then Where-Object tests each object.',['Convert JSON before filtering.','Expand the items property.','Retain only status active.'],fixture={'shell':'powershell','goal':'active-json'})
for id,title,kind,task,solution,goal in [
 ('v2-git-stage','Commit only the intended pipeline change','staging','Stage and commit pipeline.py, but keep notes.md out of the commit. Inspect the working tree, index and diff before committing.','git status\ngit add pipeline.py\ngit diff --cached\ngit commit -m "Validate pipeline"','staged-only'),
 ('v2-git-merge','Merge two lines of work without rewriting history','merge','Merge feature into main. Inspect the resulting commit parents and verify that the feature branch remains at E.','git status\ngit merge feature','merge'),
 ('v2-git-rebase','Replay a feature branch on the new main','rebase','While on feature, rebase onto main. Compare old D/E with the new IDs and inspect the new parent chain.','git rebase main','rebase'),
 ('v2-git-fetch','Fetch is not pull','remote','Fetch the remote fixture. origin/main should advance to R while local main and working files stay at C. Then explain the difference from pull.','git fetch','fetch'),
 ('v2-git-conflict','Resolve a merge conflict and complete the graph','conflict','Merge feature into main. Resolve pipeline.py with the file editor, stage it, and make the merge commit. Do not leave conflict markers.','git merge feature\n# Edit pipeline.py in Working tree\ngit add pipeline.py\ngit commit -m "Resolve validation merge"','merge'),
 ('v2-git-detached','Give detached work a branch name','detached','HEAD is detached at B. Create and switch to rescue so future commits have a branch ref. Select B in the graph to inspect it.','git switch -c rescue','rescue')]:
 add(id,title,'architecture','Git','git-visual',task,'',solution,'The graph is generated from the same simulated commit snapshots and refs as the terminal. Merge preserves parent histories; rebase creates new commit identities. This is deterministic teaching state, not the host Git binary.',['Inspect HEAD and branch refs.','Verify index and working tree.','Explain whether history is preserved or rewritten.'],difficulty='Easy' if kind in ['staging','remote','detached'] else 'Medium',fixture={'git':kind,'goal':goal},visual=dict(type='git-commit-graph',steps=['Working files','git add -> index','git commit -> snapshot','Branch ref / HEAD'],detail='Refs point to commit identities; they are not folders. The staged snapshot can differ from working files.'))
add('v2-cloud-compare','Choose a platform from constraints','architecture','Cloud architecture','architecture-editor','Design for 4 TB/day, latency under 5 minutes, EU PII residency and a SQL-heavy BI team. Compare Fabric and Databricks without treating platform names as a design.','source[Sources] -> ingest[Ingestion]\ningest -> store[Governed storage]\nstore -> semantic[Semantic serving]\nsemantic -> report[BI]\n# Add monitoring and access boundaries.','Define ingestion latency, replay and quality gates, a governed curated store, semantic serving and monitoring.\nFabric may fit integrated Power BI operations; Databricks may fit complex Spark transformations. Validate region support, governance, team capability, cost and workload benchmarks.','Objective structure checks are separate from subjective trade-offs. A connected diagram cannot prove residency, cost or a latency SLA.',['Ingestion, storage, semantic and report roles.','Explicit PII access / residency boundary.','Explain cost and operational trade-offs.'],template='fabric',fixture={'constraints':{'Daily volume':'4 TB','Latency':'< 5 min','Retention':'7 years','PII':'Yes','Residency':'EU','Team':'SQL-heavy','Cost sensitivity':'High'},'comparison':[{'criterion':'Primary workload','Fabric':'Integrated analytics + BI','Databricks':'Engineering + Spark workloads'},{'criterion':'Decision evidence','Fabric':'Measure semantic refresh and ingestion path','Databricks':'Measure pipeline and serving path'},{'criterion':'Not inferred','Fabric':'Automatic low cost or residency compliance','Databricks':'Automatic scalability or exactly-once semantics'}]})
add('v2-concept-watermark','A watermark is not a deduplication key','pipeline','Airflow','concept-case','The copy succeeded but the watermark write failed. The next run repeats the interval. Explain how to avoid lost rows and duplicates, including late arrivals.','Read boundary:\nWrite strategy:\nCommit boundary:\nLate-arrival policy:', 'Capture an upper boundary before extraction; use an overlap/lookback or CDC policy for late updates. Deduplicate by stable business key and version, then commit destination and advance control state after validation. Retrying the same range must be safe.','A watermark tracks extraction progress. It does not prevent duplicated target rows. Exactly-once business results require a complete correctness argument across failure boundaries.',['Separate progress from row identity.','Make replay idempotent.','Describe a late-arrival policy.'],visual=dict(type='flow',steps=['Read old/high bounds','Extract bounded interval','Idempotent target write','Validate','Advance watermark'],detail='If the last step fails, replay the interval safely; never skip ahead before the target is valid.'))
add('v2-concept-shuffle','Which transformation needs data movement?','code','PySpark','multi-choice-reasoning','Choose the operation most likely to require redistributing records across executors when input is not already suitably partitioned. Explain your choice.','Your reasoning:', 'groupBy(customer_id).sum(amount) generally requires an exchange so records with the same key can meet. A select or a simple filter is normally narrow. The actual optimized physical plan is authoritative.', 'A shuffle redistributes records across partitions. An action triggers execution but is not itself a synonym for a shuffle. Existing partitioning and optimizer choices can change the actual plan.',['Distinguish transformation from action.','State the grouping-key requirement.','Verify the actual plan.'],difficulty='Easy',fixture={'options':[{'id':'select','label':'select("customer_id")'},{'id':'group','label':'groupBy("customer_id").sum("amount")'},{'id':'filter','label':'filter(amount > 0)'}],'answer':'group'},visual=dict(type='spark-stage',steps=['Input partitions','Exchange by customer','Grouped records','Aggregate'],detail='Records sharing a group key must be co-located for the final aggregation.'))
# Expected SQL fixture outputs are computed using SQLite only for this portable SELECT subset.
fixtures=json.loads((ROOT/'public/packs/fixtures.json').read_text())
for q in old+new:
 if q['engine']=='sql':
  tests=[]
  for label,overrides in [('Base fixture',{}),('Empty orders',{'orders':[]}),('Same-date tie and repeated paid amount',{'orders':fixtures['orders']['rows']+[dict(order_id=106,customer_id=1,order_date='2026-01-05',amount=80,status='paid')]})]:
   conn=sqlite3.connect(':memory:')
   for name,t in fixtures.items():
    if name not in ['customers','orders']:continue
    cols=t['columns'];conn.execute('CREATE TABLE "'+name+'" ('+','.join('"'+c['name']+'" '+c['type'] for c in cols)+')')
    rows=overrides.get(name,t['rows'])
    conn.executemany('INSERT INTO "'+name+'" VALUES ('+','.join('?' for _ in cols)+')',[[r[c['name']] for c in cols] for r in rows])
   cur=conn.execute(q['solution']);tests.append(dict(label=label,overrides=overrides,columns=[x[0] for x in cur.description],rows=[list(r) for r in cur.fetchall()]));conn.close()
  q['fixture']={**q.get('fixture',{}),'sqlTests':tests}
# Verified notebook section references, with no invented workspace URLs.
map_specs={
 'spark-dedup':('03 - PySpark DataFrame Interview Arena','C2. Latest row per customer'),
 'v2-spark-aggregate':('03 - PySpark DataFrame Interview Arena','B2. groupBy + agg'),
 'v2-spark-join':('03 - PySpark DataFrame Interview Arena','C1. Join a dimension'),
 'python-aggregate':('01 - Python Core Interview Arena','B2. Count by key with a dictionary'),
 'v2-python-latest':('01 - Python Core Interview Arena','C1. Latest record per key'),
 'pandas-grain':('02 - Pandas and NumPy Data Wrangling Arena','C1. Revenue and order count by country'),
 'sql-paid-revenue':('01 - SQL Interview Arena','CSI-01 \u2014 Retail Orders'),
 'sql-latest-order':('02 - SQL Patterns Optimization and Interview Playbook','B3. Window functions are row-preserving analytics'),
 'bi-revenue':('01 - BI Analytics Engineering - dbt DAX Power BI','C1. Revenue'),
 'bi-filter-context':('01 - BI Analytics Engineering - dbt DAX Power BI','D1. Filter context'),
 'adf-watermark':('03 - Airflow Pipeline and SQL Data Engineering Arena','D1. Advance the watermark safely'),
 'dag-idempotency':('03 - Airflow Pipeline and SQL Data Engineering Arena','C2. Commit then retry'),
}
# Historical section labels are retained as blank-URL metadata only. The V2.2 fixture checker checks this metadata, not a notebook archive.
for q in old+new:
 if q['renderer']=='sql-editor' and q['engine']!='sql':q['executionMode']='review'
 if q['id']=='v2-dbt-failure':q['solution']=q['starter'].replace('-- Keep one deterministic row', 'SELECT * EXCLUDE(rn) FROM ranked WHERE rn = 1;') + '\n-- Rerun unique and not_null tests before publishing.'
 if q['id'] in map_specs:
  notebook,section=map_specs[q['id']];q['deepnoteLinks']=[dict(type='exercise',label='Open companion notebook',url='',exerciseRef=section,notebook=notebook)]
for name,pack in [('starter',dict(schemaVersion=2,id='studio-starter',title='Data engineering foundations',version=2,questions=old)),('v2-specialists',dict(schemaVersion=2,id='studio-v2-specialists',title='V2 specialist interview labs',version=1,questions=new))]:
 (ROOT/f'public/packs/{name}.json').write_text(json.dumps(pack,indent=2,ensure_ascii=False)+'\n')
(ROOT/'public/packs/index.json').write_text(json.dumps({'packs':['starter.json','v2-specialists.json']},indent=2))
(ROOT/'public/packs/deepnote-mapping.json').write_text(json.dumps({'schemaVersion':1,'links':{q['id']:q['deepnoteLinks'] for q in old+new if q['deepnoteLinks']}},indent=2))
(ROOT/'docs/baseline-stable-ids.json').write_text(json.dumps([q['id'] for q in old],indent=2))
print(f'{len(old)} v1 IDs preserved; {len(new)} new examples; {len(old)+len(new)} total.')
