import type { CaseSession } from './case-study/controller.js';
import type { Presentation } from './shell/layout-controller.js';
export type Workspace = 'code'|'model'|'pipeline'|'architecture';
export type Engine = 'sql'|'python'|'dax-subset'|'graph'|'review';
export type Renderer = 'sql-editor'|'code-editor'|'pyspark-editor'|'semantic-model'|'dag-editor'|'pipeline-investigation'|'architecture-editor'|'performance-investigation'|'config-editor'|'terminal'|'git-visual'|'multi-choice-reasoning'|'concept-case';
export type ExecutionMode = 'execute'|'analyze'|'simulate'|'review'|'external';
export type Row = Record<string,string|number|boolean|null>;
export interface GraphNode {id:string;label:string;role:string;x:number;y:number;fields?:string[];duration?:number;retries?:number;retryDelay?:number;transient?:boolean;triggerRule?:string;skip?:boolean;pool?:string;[key:string]:unknown;}
export interface GraphEdge {id:string;from:string;to:string;label?:string;active?:boolean;condition?:string;cardinality?:string;direction?:string;fromColumn?:string;toColumn?:string;}
export interface Graph {nodes:GraphNode[];edges:GraphEdge[];}
export interface DeepnoteLink {type:'exercise'|'concept'|'mock'|'reference'|'project';label:string;url:string;exerciseRef?:string;notebook?:string;}
export interface Question {id:string;version:number;title:string;workspace:Workspace;topic:string;difficulty:'Easy'|'Medium'|'Hard';minutes:number;engine:Engine;language:string;summary:string;concept:string[];task:string;requirements:string[];starter:string;solution:string;explanation:string;hints:string[];sources:{label:string;url:string}[];dataset?:string;ordered?:boolean;template?:string;rubric?:string[];expectedGrain?:string;pythonTests?:{args:unknown[];expected:unknown;label:string}[];entrypoint?:string;technology?:string;renderer?:Renderer;executionMode?:ExecutionMode;interviewPriority?:string;followUps?:string[];deepnoteUrl?:string;deepnoteLabel?:string;deepnoteMode?:'notebook'|'app'|'reference';deepnoteLinks?:DeepnoteLink[];deepnoteEmbedUrl?:string|null;fixture?:Record<string,any>;visual?:{type:string;steps?:string[];mermaid?:string;detail?:string};[key:string]:unknown;}
export interface Pack {schemaVersion:1|2;id:string;title:string;version:number;questions:Question[];}
export interface Attempt {at:string;kind:string;passed:boolean|null;summary:string;code?:string;}
export interface Draft {code?:string;notes?:string;graph?:Graph;bookmark?:boolean;confidence?:'New'|'Learning'|'Review'|'Confident';status?:'not-started'|'in-progress'|'completed'|'review';attempts?:Attempt[];updatedAt?:string;rubric?:string[];country?:string;category?:string;grain?:string;diagram?:string;selectedTable?:string;performance?:{partitions:number;skew:number;broadcast:boolean};labState?:any;diagnosis?:string;answer?:string;[key:string]:unknown;}
export interface Store {schemaVersion:1;drafts:Record<string,Draft>;customPacks:Pack[];caseSessions?:Record<string,CaseSession>;settings:{focus:boolean;workstation?:Presentation;activeCase?:string;lastQuestion?:string;pyodideConsent?:boolean;runtimeConsent?:boolean;split?:number;drawerHeight?:number;drawerCollapsed?:boolean;deepnoteMap?:Record<string,DeepnoteLink[]>;[key:string]:unknown};v2?:{version:number;migratedAt:string};}
export interface QueryResult {engine:string;mode?:ExecutionMode;columns:string[];rows:unknown[][];elapsedMs:number;truncated?:boolean;error?:string;notice?:string;checks?:{label:string;passed:boolean;detail:string;actual?:unknown[][];expected?:unknown[][];columns?:string[];actualColumns?:string[]}[];output?:string;}
export interface Fixtures {[name:string]:{columns:{name:string;type:string}[];rows:Row[]};}
